# Generated by Django 4.2.7 on 2023-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='equipement',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
